INSERT INTO taxiapp.locations (location_name) VALUES ('Хортицький');
INSERT INTO taxiapp.locations (location_name) VALUES ('Дніпровський');
INSERT INTO taxiapp.locations (location_name) VALUES ('Комунарський');
INSERT INTO taxiapp.locations (location_name) VALUES ('Олександрівський');
INSERT INTO taxiapp.locations (location_name) VALUES ('Вознесенівський');
INSERT INTO taxiapp.locations (location_name) VALUES ('Шевченківський');
INSERT INTO taxiapp.locations (location_name) VALUES ('Заводський');

INSERT INTO taxiapp.distances (location_1, location_2, distance) VALUES (1, 1, '1');
INSERT INTO taxiapp.distances (location_1, location_2, distance) VALUES (1, 2, '28');
INSERT INTO taxiapp.distances (location_1, location_2, distance) VALUES (1, 3, '20');
INSERT INTO taxiapp.distances (location_1, location_2, distance) VALUES (1, 4, '34');
INSERT INTO taxiapp.distances (location_1, location_2, distance) VALUES (1, 5, '31');
INSERT INTO taxiapp.distances (location_1, location_2, distance) VALUES (1, 6, '23');
INSERT INTO taxiapp.distances (location_1, location_2, distance) VALUES (1, 7, '15');
INSERT INTO taxiapp.distances (location_1, location_2, distance) VALUES (2, 2, '1');
INSERT INTO taxiapp.distances (location_1, location_2, distance) VALUES (2, 3, '17');
INSERT INTO taxiapp.distances (location_1, location_2, distance) VALUES (2, 4, '26');
INSERT INTO taxiapp.distances (location_1, location_2, distance) VALUES (2, 5, '34');
INSERT INTO taxiapp.distances (location_1, location_2, distance) VALUES (2, 6, '25');
INSERT INTO taxiapp.distances (location_1, location_2, distance) VALUES (2, 7, '32');
INSERT INTO taxiapp.distances (location_1, location_2, distance) VALUES (3, 3, '1');
INSERT INTO taxiapp.distances (location_1, location_2, distance) VALUES (3, 4, '19');
INSERT INTO taxiapp.distances (location_1, location_2, distance) VALUES (3, 5, '17');
INSERT INTO taxiapp.distances (location_1, location_2, distance) VALUES (3, 6, '8');
INSERT INTO taxiapp.distances (location_1, location_2, distance) VALUES (3, 7, '15');
INSERT INTO taxiapp.distances (location_1, location_2, distance) VALUES (4, 4, '1');
INSERT INTO taxiapp.distances (location_1, location_2, distance) VALUES (4, 5, '19');
INSERT INTO taxiapp.distances (location_1, location_2, distance) VALUES (4, 6, '18');
INSERT INTO taxiapp.distances (location_1, location_2, distance) VALUES (4, 7, '19');
INSERT INTO taxiapp.distances (location_1, location_2, distance) VALUES (5, 5, '1');
INSERT INTO taxiapp.distances (location_1, location_2, distance) VALUES (5, 6, '14');
INSERT INTO taxiapp.distances (location_1, location_2, distance) VALUES (5, 7, '21');
INSERT INTO taxiapp.distances (location_1, location_2, distance) VALUES (6, 6, '1');
INSERT INTO taxiapp.distances (location_1, location_2, distance) VALUES (6, 7, '10');
INSERT INTO taxiapp.distances (location_1, location_2, distance) VALUES (7, 7, '1');

INSERT IGNORE INTO taxiapp.car_type (type_name) VALUES ('CHEAP');
INSERT IGNORE INTO taxiapp.car_type (type_name) VALUES ('COMFORT');
INSERT IGNORE INTO taxiapp.car_type (type_name) VALUES ('BUSINESS');

INSERT IGNORE INTO taxiapp.status (status) VALUES ('FREE');
INSERT IGNORE INTO taxiapp.status (status) VALUES ('BUSY');
INSERT IGNORE INTO taxiapp.status (status) VALUES ('UNAVAILABLE');

INSERT IGNORE INTO taxiapp.roles (role_name) VALUES ('ADMIN');
INSERT IGNORE INTO taxiapp.roles (role_name) VALUES ('USER');

INSERT INTO taxiapp.cars (car_name, cost, status_id, type_id, passengers) VALUES ('Beige Suzuki Maruti 800', '40', 1, 1, 2);
INSERT INTO taxiapp.cars (car_name, cost, status_id, type_id, passengers) VALUES ('Blue Hyundai i10', '40', 1, 1, 2);
INSERT INTO taxiapp.cars (car_name, cost, status_id, type_id, passengers) VALUES ('Black Honda Accord', '50', 1, 1, 4);
INSERT INTO taxiapp.cars (car_name, cost, status_id, type_id, passengers) VALUES ('White Volkswagen Routan', '60', 1, 1, 6);
INSERT INTO taxiapp.cars (car_name, cost, status_id, type_id, passengers) VALUES ('Red Honda CR-Z', '150', 1, 2, 2);
INSERT INTO taxiapp.cars (car_name, cost, status_id, type_id, passengers) VALUES ('Black Toyota Camry', '175', 1, 2, 4);
INSERT INTO taxiapp.cars (car_name, cost, status_id, type_id, passengers) VALUES ('Silver Audi A5', '175', 1, 2, 4);
INSERT INTO taxiapp.cars (car_name, cost, status_id, type_id, passengers) VALUES ('White Shkoda Octavia', '175', 1, 2, 4);
INSERT INTO taxiapp.cars (car_name, cost, status_id, type_id, passengers) VALUES ('White Fiat Scudo', '200', 1, 2, 6);
INSERT INTO taxiapp.cars (car_name, cost, status_id, type_id, passengers) VALUES ('Silver Opel Astra G', '200', 1, 2, 6);
INSERT INTO taxiapp.cars (car_name, cost, status_id, type_id, passengers) VALUES ('Red Smart Roadster', '300', 1, 3, 2);
INSERT INTO taxiapp.cars (car_name, cost, status_id, type_id, passengers) VALUES ('Black Mercedes Benz', '325', 1, 3, 4);
INSERT INTO taxiapp.cars (car_name, cost, status_id, type_id, passengers) VALUES ('Silver BMW X7', '350', 1, 3, 6);
